FROM node:alpine

WORKDIR /app

COPY package.json .


RUN npm install --unsafe-perm=true --allow-root

COPY . .

# uncomment following two lines if you are not using docker-compose
# RUN chown -Rh node /app/node_modules

# USER node

CMD ["npm", "start"]